= SailPoint extended
:toc:
:toclevels: 5

== Description
Contains features for extending IdentityIQ 8.0

== Structure
. *sailpoint-build* - module for starting build command in ssd.
. *sailpoint-extended* - main module for extending. Contains all configurations.
. *sailpoint-extended-common* - common module for all features. Contains common stuff like: mappers, spring context provider, etc.
. *sailpoint-extended-model* - contains custom model entities and repositories.
. *sailpoint-extended-rest* - contains custom rest controller, mapper and entity for it.
. *sailpoint-vaadin-plugin* - module for building plugin for IdentityIQ with Vaadin UI.
. *sailpoint-vaadin-ui* - all Vaadin UI components.

== Properties
Main properties:

. *sailpoint.environment.target* - sailpoint build environment value.
. *sailpoint.build.directory.path* - absolute path to SSD.

== Building
Before building project install:

. nodejs 10+
. npm

This is very important for using Vaadin UI.

Command:
----
mvn clean install -Dsailpoint
----
Where "-Dsailpoint" enable building identityiq.war