{
 "title": "Identity IQ",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "IIQHost", "label": "IIQ Host", "query": "iiqhost1,iiqhost2" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage $IIQHost",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "repeat": "IIQHost",
   "targets": [
    {
     "expr": "cpuUsage{host_name=\"$IIQHost\"} "
    }
   ]
  },
  {
   "title": "CPU usage $IIQHost",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "cpuUsage{host_name=\"$IIQHost\"} "
    }
   ]
  },
  {
   "title": "RAM usage $IIQHost",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "repeat": "IIQHost",
   "targets": [
    {
     "expr": "memoryUsagePercentage{host_name=\"$IIQHost\"}"
    }
   ]
  },
  {
   "title": "RAM usage $IIQHost",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "memoryUsagePercentage{host_name=\"$IIQHost\"}"
    }
   ]
  },
  {
   "title": "Active tasks duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sort(avg(active_tasks) by (active_task_name))",
     "legendFormat": "{{active_task_name}}"
    }
   ]
  }
 ]
}